spring:
  application:
    name: rappideliverer
server:
  port: ${PORT:8083}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
